name: The Nordic Escape
favicon: null
layout_spectrum: 0.5079
typography_spectrum: 0.13954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#89a8ba'
    - '#006ab8'
    - '#000000'
    - '#f4f0ec'
    - '#7f6327'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.6570231856312603
purpose: []
